export const CB_CARRIERS = [
  "State Farm",
  "Allstate",
  "USAA",
  "Farmers",
  "Liberty Mutual",
  "American Family",
  "Travelers",
  "Nationwide",
  "Progressive",
  "Erie Insurance",
  "Chubb",
  "Auto-Owners",
  "The Hartford",
  "Safeco",
  "Country Financial",
  "Amica",
  "Cincinnati Insurance",
  "Shelter Insurance",
  "Westfield",
  "Foremost",
  "Citizens Property Insurance",
  "Universal Property",
  "Heritage Property & Casualty",
  "Tower Hill",
  "Homeowners Choice",
  "Kin Insurance",
  "Openly",
  "Hippo",
  "Lemonade",
  "Encompass",
];
