/**
 * Roof system → assembly.
 *
 * The takeoff sheet field cb_takeoffs.data.sheet.roof_system.roof_type is the
 * SELECTOR for the estimate. Every system has its own assembly: its own tear
 * off, its own covering, its own underlayment and its own accessories.
 *
 * There is deliberately NO fallback. If a system has no assembly the estimate
 * must fail loudly rather than quote a shingle price on a tile roof.
 */

export type CbQtyBasis =
  | "squares" /* true roof area, no waste */
  | "squares_waste" /* area + waste */
  | "tearoff" /* true area × layers */
  | "eave_valley"
  | "eave_rake"
  | "ridge_hip"
  | "ridge"
  | "eave"
  | "valley"
  | "perimeter";

export interface CbAssemblyLine {
  key: string;
  /** Every word must appear in the catalog item name. */
  must: string[];
  prefer?: string[];
  avoid?: string[];
  unit: string;
  label: string;
  basis: CbQtyBasis;
  /** LF quantity that becomes SF when the catalog item is sold by SF. */
  lfToSf?: boolean;
  /** Marks the line as the system's underlayment (never defaulted globally). */
  role?: "tearoff" | "covering" | "underlayment" | "accessory";
}

export interface CbAssembly {
  key: string;
  label: string;
  /** Lower-cased fragments of the takeoff value that select this assembly. */
  aliases: string[];
  lines: CbAssemblyLine[];
}

const tearoff = (must: string[], label: string, prefer?: string[]): CbAssemblyLine => ({
  key: "tearoff",
  must,
  prefer,
  avoid: ["ridge", "starter"],
  unit: "SQ",
  label,
  basis: "tearoff",
  role: "tearoff",
});

const iws: CbAssemblyLine = {
  key: "iws",
  must: ["ice"],
  prefer: ["water barrier", "water shield"],
  avoid: ["remove"],
  unit: "SF",
  label: "Ice & water barrier",
  basis: "eave_valley",
  lfToSf: true,
  role: "accessory",
};

export const CB_ASSEMBLIES: CbAssembly[] = [
  {
    key: "shingle_3tab",
    label: "3-tab asphalt shingle",
    aliases: ["3-tab", "3 tab", "three tab"],
    lines: [
      tearoff(["remove", "shingle"], "Tear off existing shingles", ["3 tab", "comp."]),
      {
        key: "covering",
        must: ["shingle"],
        prefer: ["3 tab", "composition"],
        avoid: ["remove", "ridge", "hip", "starter", "laminated"],
        unit: "SQ",
        label: "3-tab composition shingles",
        basis: "squares_waste",
        role: "covering",
      },
      {
        key: "underlayment",
        must: ["felt"],
        prefer: ["15", "roofing felt"],
        avoid: ["remove"],
        unit: "SQ",
        label: "#15 felt underlayment",
        basis: "squares",
        role: "underlayment",
      },
      iws,
      {
        key: "starter",
        must: ["starter"],
        prefer: ["asphalt", "universal"],
        avoid: ["remove"],
        unit: "LF",
        label: "Starter course",
        basis: "eave_rake",
        role: "accessory",
      },
      {
        key: "ridgecap",
        must: ["ridge cap"],
        prefer: ["composition", "hip"],
        unit: "LF",
        label: "Hip & ridge cap",
        basis: "ridge_hip",
        role: "accessory",
      },
    ],
  },
  {
    key: "shingle_arch",
    label: "Architectural asphalt shingle",
    aliases: ["architectural", "laminated", "dimensional", "asphalt shingle", "composition shingle"],
    lines: [
      tearoff(["remove", "shingle"], "Tear off existing shingles", ["laminated", "comp."]),
      {
        key: "covering",
        must: ["laminated", "shingle"],
        prefer: ["comp."],
        avoid: ["remove", "ridge", "hip"],
        unit: "SQ",
        label: "Laminated composition shingles",
        basis: "squares_waste",
        role: "covering",
      },
      {
        key: "underlayment",
        must: ["underlayment"],
        prefer: ["synthetic"],
        avoid: ["remove", "plywood", "lauan", "pad", "floor"],
        unit: "SQ",
        label: "Synthetic underlayment",
        basis: "squares",
        role: "underlayment",
      },
      iws,
      {
        key: "starter",
        must: ["starter"],
        prefer: ["asphalt", "universal"],
        avoid: ["remove"],
        unit: "LF",
        label: "Starter course",
        basis: "eave_rake",
        role: "accessory",
      },
      {
        key: "ridgecap",
        must: ["ridge cap"],
        prefer: ["composition", "hip"],
        unit: "LF",
        label: "Hip & ridge cap",
        basis: "ridge_hip",
        role: "accessory",
      },
    ],
  },
  {
    key: "shingle_luxury",
    label: "Luxury / designer asphalt shingle",
    aliases: ["luxury", "designer"],
    lines: [
      tearoff(["remove", "shingle"], "Tear off existing shingles", ["laminated"]),
      {
        key: "covering",
        must: ["shingle"],
        prefer: ["laminated", "high grade", "designer"],
        avoid: ["remove", "ridge", "hip", "starter"],
        unit: "SQ",
        label: "Designer / luxury shingles",
        basis: "squares_waste",
        role: "covering",
      },
      {
        key: "underlayment",
        must: ["underlayment"],
        prefer: ["synthetic"],
        avoid: ["remove", "plywood", "lauan", "pad", "floor"],
        unit: "SQ",
        label: "Synthetic underlayment",
        basis: "squares",
        role: "underlayment",
      },
      iws,
      {
        key: "starter",
        must: ["starter"],
        prefer: ["asphalt", "universal"],
        avoid: ["remove"],
        unit: "LF",
        label: "Starter course",
        basis: "eave_rake",
        role: "accessory",
      },
      {
        key: "ridgecap",
        must: ["ridge cap"],
        prefer: ["composition", "hip"],
        unit: "LF",
        label: "Hip & ridge cap",
        basis: "ridge_hip",
        role: "accessory",
      },
    ],
  },
  {
    key: "shingle_ir",
    label: "Impact-resistant shingle",
    aliases: ["impact-resistant", "impact resistant", "class 4"],
    lines: [
      tearoff(["remove", "shingle"], "Tear off existing shingles", ["laminated"]),
      {
        key: "covering",
        must: ["shingle"],
        prefer: ["impact", "class 4", "laminated"],
        avoid: ["remove", "ridge", "hip", "starter"],
        unit: "SQ",
        label: "Impact-resistant shingles",
        basis: "squares_waste",
        role: "covering",
      },
      {
        key: "underlayment",
        must: ["underlayment"],
        prefer: ["synthetic"],
        avoid: ["remove", "plywood", "lauan", "pad", "floor"],
        unit: "SQ",
        label: "Synthetic underlayment",
        basis: "squares",
        role: "underlayment",
      },
      iws,
      {
        key: "starter",
        must: ["starter"],
        prefer: ["asphalt", "universal"],
        avoid: ["remove"],
        unit: "LF",
        label: "Starter course",
        basis: "eave_rake",
        role: "accessory",
      },
      {
        key: "ridgecap",
        must: ["ridge cap"],
        prefer: ["composition", "hip"],
        unit: "LF",
        label: "Hip & ridge cap",
        basis: "ridge_hip",
        role: "accessory",
      },
    ],
  },
  {
    key: "tile_concrete",
    label: "Concrete tile",
    aliases: ["concrete tile"],
    lines: [
      tearoff(["remove", "tile"], "Tear off existing tile roofing", ["concrete"]),
      {
        key: "covering",
        must: ["tile"],
        prefer: ["concrete"],
        avoid: ["remove", "clay", "ridge", "hip", "underlayment"],
        unit: "SQ",
        label: "Concrete tile roofing",
        basis: "squares_waste",
        role: "covering",
      },
      {
        key: "underlayment",
        must: ["ice or water"],
        prefer: ["modified", "bitumen", "barrier"],
        avoid: ["remove"],
        unit: "SQ",
        label: "Tile underlayment — self-adhered / modified base",
        basis: "squares",
        role: "underlayment",
      },
      {
        key: "tile_eave_closure",
        must: ["eave closure"],
        avoid: ["remove"],
        unit: "LF",
        label: "Tile eave closure",
        basis: "eave",
        role: "accessory",
      },
      {
        key: "tile_hip_ridge",
        must: ["ridge"],
        prefer: ["tile", "hip"],
        avoid: ["remove", "vent", "shingle"],
        unit: "LF",
        label: "Tile hip & ridge",
        basis: "ridge_hip",
        role: "accessory",
      },
      {
        key: "tile_setting",
        must: ["mortar"],
        prefer: ["tile", "adhesive", "foam"],
        avoid: ["remove"],
        unit: "LF",
        label: "Tile setting mortar / adhesive",
        basis: "ridge_hip",
        role: "accessory",
      },
    ],
  },
  {
    key: "tile_clay",
    label: "Clay tile",
    aliases: ["clay tile", "barrel tile", "spanish tile"],
    lines: [
      tearoff(["remove", "tile"], "Tear off existing tile roofing", ["clay"]),
      {
        key: "covering",
        must: ["tile"],
        prefer: ["clay", "barrel", "s-tile"],
        avoid: ["remove", "concrete", "ridge", "hip", "underlayment"],
        unit: "SQ",
        label: "Clay tile roofing",
        basis: "squares_waste",
        role: "covering",
      },
      {
        key: "underlayment",
        must: ["ice or water"],
        prefer: ["modified", "bitumen", "barrier"],
        avoid: ["remove"],
        unit: "SQ",
        label: "Tile underlayment — self-adhered / modified base",
        basis: "squares",
        role: "underlayment",
      },
      {
        key: "tile_eave_closure",
        must: ["eave closure"],
        avoid: ["remove"],
        unit: "LF",
        label: "Tile eave closure",
        basis: "eave",
        role: "accessory",
      },
      {
        key: "tile_hip_ridge",
        must: ["ridge"],
        prefer: ["tile", "hip"],
        avoid: ["remove", "vent", "shingle"],
        unit: "LF",
        label: "Tile hip & ridge",
        basis: "ridge_hip",
        role: "accessory",
      },
    ],
  },
  {
    key: "metal_standing_seam",
    label: "Standing seam metal",
    aliases: ["standing seam"],
    lines: [
      tearoff(["remove", "metal"], "Tear off existing metal roofing", ["roofing"]),
      {
        key: "covering",
        must: ["standing seam"],
        avoid: ["remove"],
        unit: "SQ",
        label: "Standing seam metal roofing",
        basis: "squares_waste",
        role: "covering",
      },
      {
        key: "underlayment",
        must: ["underlayment"],
        prefer: ["high temp", "high-temp", "self-adhered", "self adhered"],
        avoid: ["remove", "plywood", "lauan", "pad", "floor"],
        unit: "SQ",
        label: "High-temperature self-adhered underlayment",
        basis: "squares",
        role: "underlayment",
      },
      {
        key: "metal_ridge",
        must: ["ridge cap"],
        prefer: ["metal"],
        avoid: ["remove", "shingle", "composition"],
        unit: "LF",
        label: "Metal ridge cap",
        basis: "ridge_hip",
        role: "accessory",
      },
      {
        key: "metal_eave_trim",
        must: ["trim"],
        prefer: ["metal", "eave", "rake"],
        avoid: ["remove"],
        unit: "LF",
        label: "Metal eave / rake trim",
        basis: "eave_rake",
        role: "accessory",
      },
    ],
  },
  {
    key: "metal_exposed_fastener",
    label: "Exposed fastener metal",
    aliases: ["corrugated", "exposed fastener", "5v", "r-panel", "ribbed metal"],
    lines: [
      tearoff(["remove", "metal"], "Tear off existing metal roofing", ["roofing"]),
      {
        key: "covering",
        must: ["metal"],
        prefer: ["corrugated", "r-panel", "5v", "exposed fastener", "roofing"],
        avoid: ["remove", "standing seam", "trim", "flashing"],
        unit: "SQ",
        label: "Exposed fastener metal roofing",
        basis: "squares_waste",
        role: "covering",
      },
      {
        key: "underlayment",
        must: ["underlayment"],
        prefer: ["high temp", "high-temp", "synthetic"],
        avoid: ["remove", "plywood", "lauan", "pad", "floor"],
        unit: "SQ",
        label: "High-temperature underlayment",
        basis: "squares",
        role: "underlayment",
      },
      {
        key: "metal_ridge",
        must: ["ridge cap"],
        prefer: ["metal"],
        avoid: ["remove", "shingle", "composition"],
        unit: "LF",
        label: "Metal ridge cap",
        basis: "ridge_hip",
        role: "accessory",
      },
      {
        key: "closure_strip",
        must: ["closure"],
        prefer: ["foam", "metal"],
        avoid: ["remove"],
        unit: "LF",
        label: "Closure strips",
        basis: "eave",
        role: "accessory",
      },
    ],
  },
  {
    key: "metal_stone_coated",
    label: "Stone-coated steel",
    aliases: ["stone-coated", "stone coated"],
    lines: [
      tearoff(["remove", "metal"], "Tear off existing metal roofing", ["roofing"]),
      {
        key: "covering",
        must: ["metal"],
        prefer: ["stone coated", "stone-coated", "steel"],
        avoid: ["remove", "standing seam", "trim"],
        unit: "SQ",
        label: "Stone-coated steel roofing",
        basis: "squares_waste",
        role: "covering",
      },
      {
        key: "underlayment",
        must: ["underlayment"],
        prefer: ["high temp", "high-temp", "synthetic"],
        avoid: ["remove", "plywood", "lauan", "pad", "floor"],
        unit: "SQ",
        label: "High-temperature underlayment",
        basis: "squares",
        role: "underlayment",
      },
      {
        key: "metal_ridge",
        must: ["ridge cap"],
        prefer: ["metal"],
        avoid: ["remove", "shingle"],
        unit: "LF",
        label: "Metal ridge cap",
        basis: "ridge_hip",
        role: "accessory",
      },
    ],
  },
  {
    key: "wood_shake",
    label: "Wood shake",
    aliases: ["wood shake", "cedar shake"],
    lines: [
      tearoff(["remove", "shake"], "Tear off existing wood shakes", ["wood"]),
      {
        key: "covering",
        must: ["shake"],
        prefer: ["cedar", "wood"],
        avoid: ["remove", "ridge"],
        unit: "SQ",
        label: "Wood shake roofing",
        basis: "squares_waste",
        role: "covering",
      },
      {
        key: "underlayment",
        must: ["felt"],
        prefer: ["30", "interlayment"],
        avoid: ["remove"],
        unit: "SQ",
        label: "#30 felt interlayment",
        basis: "squares",
        role: "underlayment",
      },
      iws,
    ],
  },
  {
    key: "wood_shingle",
    label: "Wood shingle",
    aliases: ["wood shingle", "cedar shingle"],
    lines: [
      tearoff(["remove", "shingle"], "Tear off existing wood shingles", ["wood", "cedar"]),
      {
        key: "covering",
        must: ["shingle"],
        prefer: ["wood", "cedar"],
        avoid: ["remove", "laminated", "composition", "ridge"],
        unit: "SQ",
        label: "Wood shingle roofing",
        basis: "squares_waste",
        role: "covering",
      },
      {
        key: "underlayment",
        must: ["felt"],
        prefer: ["30"],
        avoid: ["remove"],
        unit: "SQ",
        label: "#30 felt underlayment",
        basis: "squares",
        role: "underlayment",
      },
      iws,
    ],
  },
  {
    key: "slate",
    label: "Slate",
    aliases: ["slate"],
    lines: [
      tearoff(["remove", "slate"], "Tear off existing slate roofing"),
      {
        key: "covering",
        must: ["slate"],
        avoid: ["remove", "synthetic"],
        unit: "SQ",
        label: "Slate roofing",
        basis: "squares_waste",
        role: "covering",
      },
      {
        key: "underlayment",
        must: ["felt"],
        prefer: ["30", "40"],
        avoid: ["remove"],
        unit: "SQ",
        label: "Heavy felt underlayment",
        basis: "squares",
        role: "underlayment",
      },
      iws,
    ],
  },
  {
    key: "slate_synthetic",
    label: "Synthetic slate",
    aliases: ["synthetic slate", "composite slate"],
    lines: [
      tearoff(["remove", "slate"], "Tear off existing slate roofing", ["synthetic"]),
      {
        key: "covering",
        must: ["slate"],
        prefer: ["synthetic", "composite"],
        avoid: ["remove"],
        unit: "SQ",
        label: "Synthetic slate roofing",
        basis: "squares_waste",
        role: "covering",
      },
      {
        key: "underlayment",
        must: ["underlayment"],
        prefer: ["synthetic"],
        avoid: ["remove", "plywood", "lauan", "pad", "floor"],
        unit: "SQ",
        label: "Synthetic underlayment",
        basis: "squares",
        role: "underlayment",
      },
      iws,
    ],
  },
  {
    key: "tpo",
    label: "TPO membrane",
    aliases: ["tpo"],
    lines: [
      tearoff(["remove", "membrane"], "Tear off existing membrane roofing", ["single ply", "tpo"]),
      {
        key: "covering",
        must: ["tpo"],
        avoid: ["remove"],
        unit: "SQ",
        label: "TPO membrane",
        basis: "squares_waste",
        role: "covering",
      },
      {
        key: "underlayment",
        must: ["insulation"],
        prefer: ["iso", "polyiso", "cover board", "roof"],
        avoid: ["remove", "attic", "blown"],
        unit: "SQ",
        label: "Polyiso insulation / cover board",
        basis: "squares",
        role: "underlayment",
      },
      {
        key: "termination",
        must: ["termination bar"],
        avoid: ["remove"],
        unit: "LF",
        label: "Termination bar",
        basis: "perimeter",
        role: "accessory",
      },
      {
        key: "edge_metal",
        must: ["edge metal"],
        avoid: ["remove"],
        unit: "LF",
        label: "Perimeter edge metal",
        basis: "perimeter",
        role: "accessory",
      },
    ],
  },
  {
    key: "epdm",
    label: "EPDM membrane",
    aliases: ["epdm", "rubber roof"],
    lines: [
      tearoff(["remove", "membrane"], "Tear off existing membrane roofing", ["single ply", "epdm"]),
      {
        key: "covering",
        must: ["epdm"],
        avoid: ["remove"],
        unit: "SQ",
        label: "EPDM membrane",
        basis: "squares_waste",
        role: "covering",
      },
      {
        key: "underlayment",
        must: ["insulation"],
        prefer: ["iso", "polyiso", "cover board", "roof"],
        avoid: ["remove", "attic", "blown"],
        unit: "SQ",
        label: "Polyiso insulation / cover board",
        basis: "squares",
        role: "underlayment",
      },
      {
        key: "edge_metal",
        must: ["edge metal"],
        avoid: ["remove"],
        unit: "LF",
        label: "Perimeter edge metal",
        basis: "perimeter",
        role: "accessory",
      },
    ],
  },
  {
    key: "pvc",
    label: "PVC membrane",
    aliases: ["pvc"],
    lines: [
      tearoff(["remove", "membrane"], "Tear off existing membrane roofing", ["single ply", "pvc"]),
      {
        key: "covering",
        must: ["pvc"],
        avoid: ["remove", "pipe", "fitting"],
        unit: "SQ",
        label: "PVC membrane",
        basis: "squares_waste",
        role: "covering",
      },
      {
        key: "underlayment",
        must: ["insulation"],
        prefer: ["iso", "polyiso", "cover board", "roof"],
        avoid: ["remove", "attic", "blown"],
        unit: "SQ",
        label: "Polyiso insulation / cover board",
        basis: "squares",
        role: "underlayment",
      },
      {
        key: "edge_metal",
        must: ["edge metal"],
        avoid: ["remove"],
        unit: "LF",
        label: "Perimeter edge metal",
        basis: "perimeter",
        role: "accessory",
      },
    ],
  },
  {
    key: "mod_bit",
    label: "Modified bitumen",
    aliases: ["modified bitumen", "mod bit", "torch down", "rolled roofing"],
    lines: [
      tearoff(["remove", "modified"], "Tear off existing modified bitumen roofing", ["bitumen"]),
      {
        key: "covering",
        must: ["modified bitumen"],
        prefer: ["cap sheet", "torch"],
        avoid: ["remove"],
        unit: "SQ",
        label: "Modified bitumen cap sheet",
        basis: "squares_waste",
        role: "covering",
      },
      {
        key: "underlayment",
        must: ["base sheet"],
        prefer: ["modified", "granulated"],
        avoid: ["remove"],
        unit: "SQ",
        label: "Modified base sheet",
        basis: "squares",
        role: "underlayment",
      },
      {
        key: "edge_metal",
        must: ["edge metal"],
        avoid: ["remove"],
        unit: "LF",
        label: "Perimeter edge metal",
        basis: "perimeter",
        role: "accessory",
      },
    ],
  },
  {
    key: "bur",
    label: "Built-up / tar and gravel",
    aliases: ["bur", "tar and gravel", "built-up", "built up"],
    lines: [
      tearoff(["remove", "built"], "Tear off existing built-up roofing", ["gravel", "up roof"]),
      {
        key: "covering",
        must: ["built"],
        prefer: ["up roofing", "gravel", "ply"],
        avoid: ["remove"],
        unit: "SQ",
        label: "Built-up roofing system",
        basis: "squares_waste",
        role: "covering",
      },
      {
        key: "underlayment",
        must: ["base sheet"],
        avoid: ["remove"],
        unit: "SQ",
        label: "Base sheet",
        basis: "squares",
        role: "underlayment",
      },
      {
        key: "edge_metal",
        must: ["edge metal"],
        avoid: ["remove"],
        unit: "LF",
        label: "Perimeter edge metal",
        basis: "perimeter",
        role: "accessory",
      },
    ],
  },
  {
    key: "spf_foam",
    label: "SPF foam",
    aliases: ["spf", "foam roof", "sprayed polyurethane", "spray foam"],
    lines: [
      {
        key: "prep",
        must: ["clean"],
        prefer: ["roof", "power wash", "pressure"],
        avoid: ["gutter"],
        unit: "SQ",
        label: "Roof preparation / cleaning",
        basis: "squares",
        role: "tearoff",
      },
      {
        key: "covering",
        must: ["foam"],
        prefer: ["polyurethane", "spf", "roof"],
        avoid: ["remove", "closure", "insulation board"],
        unit: "SQ",
        label: "Sprayed polyurethane foam",
        basis: "squares",
        role: "covering",
      },
      {
        key: "underlayment",
        must: ["primer"],
        prefer: ["roof", "coating"],
        avoid: ["remove"],
        unit: "SQ",
        label: "Substrate primer",
        basis: "squares",
        role: "underlayment",
      },
      {
        key: "topcoat",
        must: ["coating"],
        prefer: ["silicone", "acrylic", "elastomeric"],
        avoid: ["remove"],
        unit: "SQ",
        label: "Protective top coating",
        basis: "squares",
        role: "accessory",
      },
    ],
  },
  {
    key: "coating_restoration",
    label: "Coating restoration",
    aliases: ["coating", "restoration"],
    lines: [
      {
        key: "prep",
        must: ["clean"],
        prefer: ["roof", "power wash", "pressure"],
        avoid: ["gutter"],
        unit: "SQ",
        label: "Roof cleaning and prep",
        basis: "squares",
        role: "tearoff",
      },
      {
        key: "underlayment",
        must: ["primer"],
        prefer: ["roof", "coating"],
        avoid: ["remove"],
        unit: "SQ",
        label: "Coating primer",
        basis: "squares",
        role: "underlayment",
      },
      {
        key: "covering",
        must: ["coating"],
        prefer: ["silicone", "acrylic", "elastomeric"],
        avoid: ["remove"],
        unit: "SQ",
        label: "Restoration coating system",
        basis: "squares",
        role: "covering",
      },
      {
        key: "seam_reinforce",
        must: ["fabric"],
        prefer: ["polyester", "reinforc"],
        avoid: ["remove"],
        unit: "LF",
        label: "Seam reinforcing fabric",
        basis: "perimeter",
        role: "accessory",
      },
    ],
  },
];

export function findAssembly(roofType: string | null | undefined): CbAssembly | null {
  const raw = (roofType ?? "").trim().toLowerCase();
  if (!raw) return null;
  let best: CbAssembly | null = null;
  let bestLen = 0;
  for (const a of CB_ASSEMBLIES) {
    for (const alias of a.aliases) {
      if (raw.includes(alias) && alias.length > bestLen) {
        best = a;
        bestLen = alias.length;
      }
    }
  }
  return best;
}
