/**
 * Supplement: what the carrier wrote versus what the roof actually has.
 *
 * The important design decision lives in `cbScopeFromJob` below. The model is
 * never asked "what did the carrier miss?" — that question invites invention,
 * and an invented line on a document an adjuster reads is the expensive kind of
 * wrong. Instead this file derives our scope from the measurement and the
 * takeoff sheet in plain code, and the model's only job is the one thing code
 * cannot do: decide whether a carrier line written as "R&R Ridge cap - composition
 * shingles" is the same thing as our ridge cap. Gaps are then computed here,
 * from that matching, so every gap traces back to a number a rep or a
 * measurement put on the record.
 */
import { supabase } from "@/integrations/supabase/client";
import type { CbSheet } from "./cbSheet";

interface CbSupResult {
  data: unknown;
  error: { message: string } | null;
}

/** Only the builder methods this feature uses. */
export interface CbSupQuery extends PromiseLike<CbSupResult> {
  select(cols: string): CbSupQuery;
  insert(values: Record<string, unknown>): CbSupQuery;
  update(values: Record<string, unknown>): CbSupQuery;
  eq(column: string, value: unknown): CbSupQuery;
  order(column: string, opts: { ascending: boolean }): CbSupQuery;
  limit(n: number): CbSupQuery;
  maybeSingle(): PromiseLike<CbSupResult>;
  single(): PromiseLike<CbSupResult>;
}

/**
 * `cb_supplements` is newer than the checked-in generated types, and those
 * types are regenerated by the builder rather than by hand. Editing that file
 * would put the build one regeneration away from breaking, so the table is
 * reached through this one narrow, deliberately typed door instead. It is a
 * cast, but a cast at a single named place beats a hand-edit that looks
 * generated and silently disappears.
 */
export function cbSupTable(): CbSupQuery {
  return (supabase as unknown as { from(t: string): CbSupQuery }).from("cb_supplements");
}

/**
 * The measurements printed on the carrier's own sketch page.
 *
 * Xactimate measures off the same aerial data we do but their sketch is what
 * the desk adjuster will defend, so where they published a number it wins over
 * ours — arguing quantity is a fight worth losing to win the line item.
 */
export interface CbCarrierMeasure {
  total_squares?: number | null;
  ridge_lf?: number | null;
  hip_lf?: number | null;
  valley_lf?: number | null;
  eave_lf?: number | null;
  rake_lf?: number | null;
  drip_edge_lf?: number | null;
  step_flashing_lf?: number | null;
  wall_flashing_lf?: number | null;
  pitch?: string | null;
  stories?: number | null;
}

export interface CbCarrierLine {
  code: string | null;
  name: string;
  unit: string;
  qty: number;
  unit_price: number | null;
  total: number | null;
}

/** One thing this roof has, and where that claim comes from. */
export interface CbScopeItem {
  id: string;
  label: string;
  unit: string;
  qty: number;
  /** The field this came from, shown to the rep verbatim. */
  backing: string;
  /** Words a carrier might write for the same thing, to steer the match. */
  aka: string;
  /** Where the claim comes from, so the rep can weigh it. */
  origin: "carrier_sketch" | "measurement" | "takeoff" | "photo" | "code";
  /** Set on code-driven items so an adjuster can see the citation. */
  codeReference?: string;
}

/** A scope item after the price book has been asked what it costs. */
export interface CbPricedItem {
  lineItemId: string;
  code: string | null;
  name: string;
  unit: string;
  unitPrice: number;
}

export interface CbGapItem extends CbScopeItem {
  kind: "missing" | "short";
  /** What the carrier allowed, when they allowed something. */
  carrierQty: number | null;
  carrierName: string | null;
  /**
   * The price book match. Prices in that book come from the same Xactimate
   * data the carrier prices from, so an adjuster verifying a supplement line
   * is checking it against their own software's number, not ours.
   */
  priced?: CbPricedItem;
}

export interface CbSupplementRow {
  id: string;
  job_id: string;
  pdf_path: string | null;
  file_name: string | null;
  status: "uploaded" | "parsing" | "parsed" | "failed";
  parse_error: string | null;
  carrier: string | null;
  claim_number: string | null;
  carrier_total: number | null;
  lines: CbCarrierLine[];
  carrier_measure: CbCarrierMeasure;
  gaps: CbGapItem[];
  applied: string[];
  carrier_imported_at: string | null;
  created_at: string;
}

/** A measurement row, only the fields this file reads. */
export interface CbMeasureLike {
  total_squares?: number | null;
  ridge_lf?: number | null;
  ridge_cap_lf?: number | null;
  hip_lf?: number | null;
  valley_lf?: number | null;
  eave_lf?: number | null;
  rake_lf?: number | null;
  drip_edge_lf?: number | null;
  starter_lf?: number | null;
  gutter_lf?: number | null;
  step_flashing_lf?: number | null;
  wall_flashing_lf?: number | null;
  pitch?: string | null;
  stories?: number | null;
}

const n = (v: unknown): number => {
  const x = Number(v);
  return Number.isFinite(x) && x > 0 ? x : 0;
};

const round = (x: number) => Math.round(x * 10) / 10;

/**
 * Everything this roof has that a carrier estimate ought to pay for.
 *
 * Quantities prefer the carrier's own sketch. Xactimate measured the same roof
 * and their number is the one their desk adjuster will defend, so adopting it
 * removes the argument a rep cannot win and leaves only the argument worth
 * having: that the line item belongs at all. Our measurement fills in whatever
 * their sketch did not print.
 *
 * An item is only included when we have a real number for it. A field the rep
 * left blank produces no scope item, so it can never become a gap: silence in
 * the takeoff means "not inspected", not "zero".
 */
export function cbScopeFromJob(
  measure: CbMeasureLike | null | undefined,
  sheet: Partial<CbSheet> | null | undefined,
  carrier?: CbCarrierMeasure | null,
): CbScopeItem[] {
  const out: CbScopeItem[] = [];
  const add = (
    id: string,
    label: string,
    unit: string,
    qty: number,
    backing: string,
    aka: string,
    origin: CbScopeItem["origin"] = "takeoff",
  ) => {
    if (qty > 0) out.push({ id, label, unit, qty: round(qty), backing, aka, origin });
  };

  const m = measure ?? {};
  const c = carrier ?? {};
  const s = (sheet ?? {}) as Partial<CbSheet>;

  /**
   * Their number when they printed one, ours otherwise — and the label says
   * which, because a rep quoting a quantity to an adjuster needs to know whose
   * sketch it came off.
   */
  const from = (
    field: keyof CbCarrierMeasure & keyof CbMeasureLike,
    fallback?: number,
  ): { qty: number; origin: CbScopeItem["origin"]; who: string } => {
    const theirs = n(c[field] as unknown);
    if (theirs > 0) return { qty: theirs, origin: "carrier_sketch", who: "Their sketch" };
    const ours = n(m[field] as unknown) || n(fallback);
    return { qty: ours, origin: "measurement", who: "Our measurement" };
  };

  /* ── roof body ── */
  const field = from("total_squares");
  add(
    "roof_field",
    "Roof covering — remove and replace",
    "SQ",
    field.qty,
    `${field.who}: ${round(field.qty)} squares`,
    "remove and replace composition shingles, laminated, 3 tab, tear off",
    field.origin,
  );
  add(
    "underlayment",
    "Underlayment",
    "SQ",
    field.qty,
    `${field.who}: ${round(field.qty)} squares`,
    "felt, synthetic underlayment, ice and water barrier",
    field.origin,
  );

  const ridge = (() => {
    const theirs = n(c.ridge_lf) + n(c.hip_lf);
    if (theirs > 0) return { qty: theirs, origin: "carrier_sketch" as const, who: "Their sketch" };
    return {
      qty: n(m.ridge_cap_lf) || n(m.ridge_lf) + n(m.hip_lf),
      origin: "measurement" as const,
      who: "Our measurement",
    };
  })();
  add(
    "ridge_cap",
    "Ridge cap",
    "LF",
    ridge.qty,
    `${ridge.who}: ${round(ridge.qty)} LF of ridge and hip`,
    "hip and ridge cap, cut from 3 tab, ridge cap composition",
    ridge.origin,
  );

  const eave = from("eave_lf", n(m.starter_lf));
  add(
    "starter",
    "Starter course",
    "LF",
    eave.qty,
    `${eave.who}: ${round(eave.qty)} LF of eave`,
    "starter course, starter row, asphalt starter",
    eave.origin,
  );

  const drip = (() => {
    const theirs = n(c.drip_edge_lf) || n(c.eave_lf) + n(c.rake_lf);
    if (theirs > 0) return { qty: theirs, origin: "carrier_sketch" as const, who: "Their sketch" };
    return {
      qty: n(m.drip_edge_lf) || n(m.eave_lf) + n(m.rake_lf),
      origin: "measurement" as const,
      who: "Our measurement",
    };
  })();
  add(
    "drip_edge",
    "Drip edge",
    "LF",
    drip.qty,
    `${drip.who}: ${round(drip.qty)} LF of eave and rake`,
    "drip edge, eave flashing, rake metal",
    drip.origin,
  );

  const valley = from("valley_lf");
  add(
    "valley_metal",
    "Valley metal",
    "LF",
    valley.qty,
    `${valley.who}: ${round(valley.qty)} LF of valley`,
    "valley metal, W valley, open valley flashing",
    valley.origin,
  );

  const step = from("step_flashing_lf");
  add(
    "step_flashing",
    "Step flashing",
    "LF",
    step.qty,
    `${step.who}: ${round(step.qty)} LF of step flashing`,
    "step flashing, roof to wall flashing",
    step.origin,
  );

  const wall = from("wall_flashing_lf", n(s.flashing?.roof_to_wall_lf));
  add(
    "wall_flashing",
    "Roof-to-wall flashing",
    "LF",
    wall.qty,
    `${wall.who}: ${round(wall.qty)} LF`,
    "roof to wall flashing, counterflashing, headwall, sidewall",
    wall.origin,
  );

  add(
    "gutters",
    "Gutters",
    "LF",
    n(s.gutters?.lf) || n(m.gutter_lf),
    `Takeoff: ${round(n(s.gutters?.lf) || n(m.gutter_lf))} LF of gutter`,
    "gutter, aluminum gutter, seamless gutter",
  );

  /* ── steep and two-story charges, which carriers routinely leave off ── */
  const pitchNum = (() => {
    const raw = String(c.pitch ?? m.pitch ?? s.roof_system?.pitch ?? "");
    const hit = raw.match(/(\d+)\s*[/:]\s*12/);
    return hit ? Number(hit[1]) : 0;
  })();
  if (pitchNum >= 7 && field.qty > 0) {
    add(
      "steep_charge",
      "Steep roof charge",
      "SQ",
      field.qty,
      `Pitch ${pitchNum}/12`,
      "steep charge, steep slope, additional charge for steep roof 7/12 to 9/12",
      field.origin,
    );
  }
  const stories = n(c.stories) || n(m.stories) || n(s.roof_system?.stories);
  if (stories >= 2 && field.qty > 0) {
    add(
      "two_story_charge",
      "Two-story charge",
      "SQ",
      field.qty,
      `${stories} stories`,
      "high roof, two story charge, additional charge for high roof 2 stories",
      field.origin,
    );
  }

  /* ── from the takeoff sheet ── */
  add(
    "ridge_vent",
    "Ridge vent",
    "LF",
    n(s.ventilation?.ridge_vent_lf),
    `Takeoff: ${round(n(s.ventilation?.ridge_vent_lf))} LF of ridge vent`,
    "continuous ridge vent, shingle over ridge vent",
  );
  add(
    "box_vents",
    "Box vents",
    "EA",
    n(s.ventilation?.box_vent_qty),
    `Takeoff: ${n(s.ventilation?.box_vent_qty)} box vents`,
    "turtle vent, static vent, roof louver, box vent",
  );
  add(
    "turbines",
    "Turbine vents",
    "EA",
    n(s.ventilation?.turbine_qty),
    `Takeoff: ${n(s.ventilation?.turbine_qty)} turbines`,
    "turbine vent, whirlybird, wind turbine",
  );
  add(
    "power_vents",
    "Power vents",
    "EA",
    n(s.ventilation?.power_vent_qty),
    `Takeoff: ${n(s.ventilation?.power_vent_qty)} power vents`,
    "power attic vent, powered roof vent",
  );
  add(
    "soffit_vent",
    "Soffit vent",
    "LF",
    n(s.ventilation?.soffit_vent_lf),
    `Takeoff: ${round(n(s.ventilation?.soffit_vent_lf))} LF of soffit vent`,
    "soffit vent, continuous soffit vent, intake vent",
  );

  const pipes =
    n(s.penetrations?.pipe_1_5) +
    n(s.penetrations?.pipe_2) +
    n(s.penetrations?.pipe_3) +
    n(s.penetrations?.pipe_4) +
    n(s.penetrations?.pipe_6) +
    n(s.penetrations?.pipe_8);
  add(
    "pipe_jacks",
    "Pipe jacks",
    "EA",
    pipes,
    `Takeoff: ${pipes} pipe penetrations`,
    "pipe jack, flashing pipe jack, plumbing vent flashing, roof jack",
  );
  add(
    "lead_boots",
    "Lead boots",
    "EA",
    n(s.penetrations?.lead_boots),
    `Takeoff: ${n(s.penetrations?.lead_boots)} lead boots`,
    "lead pipe jack, lead flashing",
  );
  add(
    "bath_vents",
    "Bath vent caps",
    "EA",
    n(s.penetrations?.bath_vents),
    `Takeoff: ${n(s.penetrations?.bath_vents)} bath vents`,
    "bath vent cap, exhaust cap, dryer vent cap",
  );
  add(
    "kitchen_vents",
    "Kitchen vent caps",
    "EA",
    n(s.penetrations?.kitchen_vents),
    `Takeoff: ${n(s.penetrations?.kitchen_vents)} kitchen vents`,
    "kitchen exhaust cap, range vent cap",
  );

  add(
    "ice_water",
    "Ice and water shield",
    "LF",
    n(s.underlayment?.ice_water_lf),
    `Takeoff: ${round(n(s.underlayment?.ice_water_lf))} LF`,
    "ice and water barrier, self adhered membrane, peel and stick",
  );
  add(
    "decking",
    "Decking replacement",
    "EA",
    n(s.decking?.sheets_to_replace),
    `Takeoff: ${n(s.decking?.sheets_to_replace)} sheets marked for replacement`,
    "sheathing, plywood, OSB, re-sheathing, decking",
  );
  if (s.decking?.renail) {
    add(
      "renail",
      "Deck re-nail",
      "SQ",
      field.qty,
      "Takeoff: deck marked for re-nail",
      "re-nail decking, renail roof sheathing to code",
    );
  }
  add(
    "chimney_flash",
    "Chimney flashing",
    "EA",
    n(s.chimney?.count),
    `Takeoff: ${n(s.chimney?.count)} chimney`,
    "chimney flashing, reflash chimney, chimney counterflashing",
  );
  if (s.chimney?.cricket) {
    add(
      "cricket",
      "Chimney cricket",
      "EA",
      1,
      "Takeoff: cricket present",
      "cricket, saddle, chimney cricket",
    );
  }
  add(
    "skylights",
    "Skylights",
    "EA",
    Array.isArray(s.skylights) ? s.skylights.length : 0,
    `Takeoff: ${Array.isArray(s.skylights) ? s.skylights.length : 0} skylights`,
    "skylight, skylight flashing kit, sky light",
  );
  add(
    "solar_dr",
    "Solar detach and reset",
    "EA",
    s.solar?.detach_reset ? n(s.solar?.panel_count) || 1 : 0,
    `Takeoff: ${n(s.solar?.panel_count) || 1} panels, detach and reset marked`,
    "detach and reset solar panel, R&R solar",
  );
  add(
    "downspouts",
    "Downspouts",
    "EA",
    n(s.gutters?.downspout_qty),
    `Takeoff: ${n(s.gutters?.downspout_qty)} downspouts`,
    "downspout, leader, aluminum downspout",
  );
  add(
    "fascia_metal",
    "Fascia metal",
    "LF",
    n(s.edge_metal?.fascia_metal_lf),
    `Takeoff: ${round(n(s.edge_metal?.fascia_metal_lf))} LF of fascia metal`,
    "fascia wrap, aluminum fascia, drip edge fascia",
  );

  return out;
}

/**
 * Turn the model's line-matching into gaps.
 *
 * `SHORT_BY` is the slack before an under-allowed quantity is worth arguing
 * about. Carriers round and so do we; flagging a 3% difference trains a rep to
 * ignore the list, which costs more than the 3%.
 */
const SHORT_BY = 0.9;

export function cbGapsFrom(
  scope: CbScopeItem[],
  lines: CbCarrierLine[],
  matches: { id: string; lineIndex: number | null }[],
): CbGapItem[] {
  const byId = new Map(matches.map((mm) => [mm.id, mm.lineIndex]));
  const gaps: CbGapItem[] = [];

  for (const item of scope) {
    const idx = byId.get(item.id);
    const line = idx === null || idx === undefined ? null : lines[idx];

    if (!line) {
      gaps.push({ ...item, kind: "missing", carrierQty: null, carrierName: null });
      continue;
    }
    /* Units have to agree before quantities can be compared at all — an "EA"
       allowance against our "LF" is not a short payment, it is a different
       thing, and calling it short would be a false claim. */
    if (line.unit.toUpperCase() !== item.unit.toUpperCase()) continue;
    if (line.qty < item.qty * SHORT_BY) {
      gaps.push({
        ...item,
        kind: "short",
        carrierQty: line.qty,
        carrierName: line.name,
      });
    }
  }

  return gaps;
}
