/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileSetupRouteImport } from './routes/profile-setup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as PayTokenRouteImport } from './routes/pay.$token'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as ApiTrainFromPdfRouteImport } from './routes/api.train-from-pdf'
import { Route as ApiSolarRoofExtractRouteImport } from './routes/api.solar-roof-extract'
import { Route as ApiParseXactimatePdfRouteImport } from './routes/api.parse-xactimate-pdf'
import { Route as ApiMapboxTokenRouteImport } from './routes/api.mapbox-token'
import { Route as ApiImportAssemblyPdfRouteImport } from './routes/api.import-assembly-pdf'
import { Route as ApiCalibrateSolarRouteImport } from './routes/api.calibrate-solar'
import { Route as ApiBuildRoofEstimateRouteImport } from './routes/api.build-roof-estimate'
import { Route as ApiAutoAddPhotoSuggestionsRouteImport } from './routes/api.auto-add-photo-suggestions'
import { Route as ApiApplyAssemblyImportRouteImport } from './routes/api.apply-assembly-import'
import { Route as ApiAnalyzeRoofConditionRouteImport } from './routes/api.analyze-roof-condition'
import { Route as ApiAnalyzePropertyRouteImport } from './routes/api.analyze-property'
import { Route as ApiAnalyzeJobPhotosRouteImport } from './routes/api.analyze-job-photos'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTrainingRouteImport } from './routes/admin.training'
import { Route as AdminTenantsRouteImport } from './routes/admin.tenants'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminPriceBooksRouteImport } from './routes/admin.price-books'
import { Route as AdminMembershipsRouteImport } from './routes/admin.memberships'
import { Route as AdminMeasurementReviewsRouteImport } from './routes/admin.measurement-reviews'
import { Route as AdminMacrosRouteImport } from './routes/admin.macros'
import { Route as AdminFeaturesRouteImport } from './routes/admin.features'
import { Route as AdminEmailsRouteImport } from './routes/admin.emails'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminCompaniesRouteImport } from './routes/admin.companies'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AppTeamRouteImport } from './routes/_app.team'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppPriceBooksRouteImport } from './routes/_app.price-books'
import { Route as AppLeadsRouteImport } from './routes/_app.leads'
import { Route as AppClientsRouteImport } from './routes/_app.clients'
import { Route as AppCardRouteImport } from './routes/_app.card'
import { Route as AppTeamIndexRouteImport } from './routes/_app.team.index'
import { Route as AppLeadsIndexRouteImport } from './routes/_app.leads.index'
import { Route as AppJobsIndexRouteImport } from './routes/_app.jobs.index'
import { Route as AppInvoicesIndexRouteImport } from './routes/_app.invoices.index'
import { Route as ApiPublicSignRouteImport } from './routes/api/public/sign'
import { Route as AdminPriceBooksNewRouteImport } from './routes/admin.price-books.new'
import { Route as AdminCompaniesIdRouteImport } from './routes/admin.companies.$id'
import { Route as AdminAssembliesImportRouteImport } from './routes/admin.assemblies.import'
import { Route as AppTeamRequestsRouteImport } from './routes/_app.team.requests'
import { Route as AppTeamInvitesRouteImport } from './routes/_app.team.invites'
import { Route as AppPriceBooksNewRouteImport } from './routes/_app.price-books.new'
import { Route as AppLeadsWizardRouteImport } from './routes/_app.leads.wizard'
import { Route as AppLeadsTrainingRouteImport } from './routes/_app.leads.training'
import { Route as AppLeadsSavingsRouteImport } from './routes/_app.leads.savings'
import { Route as AppLeadsPipelineRouteImport } from './routes/_app.leads.pipeline'
import { Route as AppLeadsMapRouteImport } from './routes/_app.leads.map'
import { Route as AppLeadsListRouteImport } from './routes/_app.leads.list'
import { Route as AppLeadsImportRouteImport } from './routes/_app.leads.import'
import { Route as AppLeadsFollowupRouteImport } from './routes/_app.leads.followup'
import { Route as AppJobsNewRouteImport } from './routes/_app.jobs.new'
import { Route as AppJobsIdRouteImport } from './routes/_app.jobs.$id'
import { Route as AppInvoicesNewRouteImport } from './routes/_app.invoices.new'
import { Route as AppInvoicesIdRouteImport } from './routes/_app.invoices.$id'
import { Route as AppClientsIdRouteImport } from './routes/_app.clients.$id'
import { Route as AppJobsIdIndexRouteImport } from './routes/_app.jobs.$id.index'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as AppJobsIdReportRouteImport } from './routes/_app.jobs.$id.report'
import { Route as AppJobsIdPhotosRouteImport } from './routes/_app.jobs.$id.photos'
import { Route as AppJobsIdOrderFormRouteImport } from './routes/_app.jobs.$id.order-form'
import { Route as AppJobsIdMeasureRouteImport } from './routes/_app.jobs.$id.measure'
import { Route as AppJobsIdInvoicesRouteImport } from './routes/_app.jobs.$id.invoices'
import { Route as AppJobsIdEstimateRouteImport } from './routes/_app.jobs.$id.estimate'
import { Route as AppJobsIdDocumentsRouteImport } from './routes/_app.jobs.$id.documents'
import { Route as AppJobsIdContractRouteImport } from './routes/_app.jobs.$id.contract'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSetupRoute = ProfileSetupRouteImport.update({
  id: '/profile-setup',
  path: '/profile-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const PayTokenRoute = PayTokenRouteImport.update({
  id: '/pay/$token',
  path: '/pay/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrainFromPdfRoute = ApiTrainFromPdfRouteImport.update({
  id: '/api/train-from-pdf',
  path: '/api/train-from-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSolarRoofExtractRoute = ApiSolarRoofExtractRouteImport.update({
  id: '/api/solar-roof-extract',
  path: '/api/solar-roof-extract',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParseXactimatePdfRoute = ApiParseXactimatePdfRouteImport.update({
  id: '/api/parse-xactimate-pdf',
  path: '/api/parse-xactimate-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMapboxTokenRoute = ApiMapboxTokenRouteImport.update({
  id: '/api/mapbox-token',
  path: '/api/mapbox-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportAssemblyPdfRoute = ApiImportAssemblyPdfRouteImport.update({
  id: '/api/import-assembly-pdf',
  path: '/api/import-assembly-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalibrateSolarRoute = ApiCalibrateSolarRouteImport.update({
  id: '/api/calibrate-solar',
  path: '/api/calibrate-solar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuildRoofEstimateRoute = ApiBuildRoofEstimateRouteImport.update({
  id: '/api/build-roof-estimate',
  path: '/api/build-roof-estimate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutoAddPhotoSuggestionsRoute =
  ApiAutoAddPhotoSuggestionsRouteImport.update({
    id: '/api/auto-add-photo-suggestions',
    path: '/api/auto-add-photo-suggestions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiApplyAssemblyImportRoute = ApiApplyAssemblyImportRouteImport.update({
  id: '/api/apply-assembly-import',
  path: '/api/apply-assembly-import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeRoofConditionRoute = ApiAnalyzeRoofConditionRouteImport.update({
  id: '/api/analyze-roof-condition',
  path: '/api/analyze-roof-condition',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzePropertyRoute = ApiAnalyzePropertyRouteImport.update({
  id: '/api/analyze-property',
  path: '/api/analyze-property',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeJobPhotosRoute = ApiAnalyzeJobPhotosRouteImport.update({
  id: '/api/analyze-job-photos',
  path: '/api/analyze-job-photos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrainingRoute = AdminTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPriceBooksRoute = AdminPriceBooksRouteImport.update({
  id: '/price-books',
  path: '/price-books',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembershipsRoute = AdminMembershipsRouteImport.update({
  id: '/memberships',
  path: '/memberships',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMeasurementReviewsRoute = AdminMeasurementReviewsRouteImport.update({
  id: '/measurement-reviews',
  path: '/measurement-reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMacrosRoute = AdminMacrosRouteImport.update({
  id: '/macros',
  path: '/macros',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeaturesRoute = AdminFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailsRoute = AdminEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompaniesRoute = AdminCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPriceBooksRoute = AppPriceBooksRouteImport.update({
  id: '/price-books',
  path: '/price-books',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppCardRoute = AppCardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamIndexRoute = AppTeamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTeamRoute,
} as any)
const AppLeadsIndexRoute = AppLeadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLeadsRoute,
} as any)
const AppJobsIndexRoute = AppJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicSignRoute = ApiPublicSignRouteImport.update({
  id: '/api/public/sign',
  path: '/api/public/sign',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPriceBooksNewRoute = AdminPriceBooksNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminPriceBooksRoute,
} as any)
const AdminCompaniesIdRoute = AdminCompaniesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCompaniesRoute,
} as any)
const AdminAssembliesImportRoute = AdminAssembliesImportRouteImport.update({
  id: '/assemblies/import',
  path: '/assemblies/import',
  getParentRoute: () => AdminRoute,
} as any)
const AppTeamRequestsRoute = AppTeamRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AppTeamRoute,
} as any)
const AppTeamInvitesRoute = AppTeamInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => AppTeamRoute,
} as any)
const AppPriceBooksNewRoute = AppPriceBooksNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppPriceBooksRoute,
} as any)
const AppLeadsWizardRoute = AppLeadsWizardRouteImport.update({
  id: '/wizard',
  path: '/wizard',
  getParentRoute: () => AppLeadsRoute,
} as any)
const AppLeadsTrainingRoute = AppLeadsTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AppLeadsRoute,
} as any)
const AppLeadsSavingsRoute = AppLeadsSavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => AppLeadsRoute,
} as any)
const AppLeadsPipelineRoute = AppLeadsPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppLeadsRoute,
} as any)
const AppLeadsMapRoute = AppLeadsMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppLeadsRoute,
} as any)
const AppLeadsListRoute = AppLeadsListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => AppLeadsRoute,
} as any)
const AppLeadsImportRoute = AppLeadsImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppLeadsRoute,
} as any)
const AppLeadsFollowupRoute = AppLeadsFollowupRouteImport.update({
  id: '/followup',
  path: '/followup',
  getParentRoute: () => AppLeadsRoute,
} as any)
const AppJobsNewRoute = AppJobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsIdRoute = AppJobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesNewRoute = AppInvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIdRoute = AppInvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsIdRoute = AppClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppClientsRoute,
} as any)
const AppJobsIdIndexRoute = AppJobsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppJobsIdRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppJobsIdReportRoute = AppJobsIdReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AppJobsIdRoute,
} as any)
const AppJobsIdPhotosRoute = AppJobsIdPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => AppJobsIdRoute,
} as any)
const AppJobsIdOrderFormRoute = AppJobsIdOrderFormRouteImport.update({
  id: '/order-form',
  path: '/order-form',
  getParentRoute: () => AppJobsIdRoute,
} as any)
const AppJobsIdMeasureRoute = AppJobsIdMeasureRouteImport.update({
  id: '/measure',
  path: '/measure',
  getParentRoute: () => AppJobsIdRoute,
} as any)
const AppJobsIdInvoicesRoute = AppJobsIdInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppJobsIdRoute,
} as any)
const AppJobsIdEstimateRoute = AppJobsIdEstimateRouteImport.update({
  id: '/estimate',
  path: '/estimate',
  getParentRoute: () => AppJobsIdRoute,
} as any)
const AppJobsIdDocumentsRoute = AppJobsIdDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppJobsIdRoute,
} as any)
const AppJobsIdContractRoute = AppJobsIdContractRouteImport.update({
  id: '/contract',
  path: '/contract',
  getParentRoute: () => AppJobsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/card': typeof AppCardRoute
  '/clients': typeof AppClientsRouteWithChildren
  '/leads': typeof AppLeadsRouteWithChildren
  '/price-books': typeof AppPriceBooksRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/team': typeof AppTeamRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/companies': typeof AdminCompaniesRouteWithChildren
  '/admin/content': typeof AdminContentRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/macros': typeof AdminMacrosRoute
  '/admin/measurement-reviews': typeof AdminMeasurementReviewsRoute
  '/admin/memberships': typeof AdminMembershipsRoute
  '/admin/price-books': typeof AdminPriceBooksRouteWithChildren
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/training': typeof AdminTrainingRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/analyze-job-photos': typeof ApiAnalyzeJobPhotosRoute
  '/api/analyze-property': typeof ApiAnalyzePropertyRoute
  '/api/analyze-roof-condition': typeof ApiAnalyzeRoofConditionRoute
  '/api/apply-assembly-import': typeof ApiApplyAssemblyImportRoute
  '/api/auto-add-photo-suggestions': typeof ApiAutoAddPhotoSuggestionsRoute
  '/api/build-roof-estimate': typeof ApiBuildRoofEstimateRoute
  '/api/calibrate-solar': typeof ApiCalibrateSolarRoute
  '/api/import-assembly-pdf': typeof ApiImportAssemblyPdfRoute
  '/api/mapbox-token': typeof ApiMapboxTokenRoute
  '/api/parse-xactimate-pdf': typeof ApiParseXactimatePdfRoute
  '/api/solar-roof-extract': typeof ApiSolarRoofExtractRoute
  '/api/train-from-pdf': typeof ApiTrainFromPdfRoute
  '/c/$slug': typeof CSlugRoute
  '/pay/$token': typeof PayTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/clients/$id': typeof AppClientsIdRoute
  '/invoices/$id': typeof AppInvoicesIdRoute
  '/invoices/new': typeof AppInvoicesNewRoute
  '/jobs/$id': typeof AppJobsIdRouteWithChildren
  '/jobs/new': typeof AppJobsNewRoute
  '/leads/followup': typeof AppLeadsFollowupRoute
  '/leads/import': typeof AppLeadsImportRoute
  '/leads/list': typeof AppLeadsListRoute
  '/leads/map': typeof AppLeadsMapRoute
  '/leads/pipeline': typeof AppLeadsPipelineRoute
  '/leads/savings': typeof AppLeadsSavingsRoute
  '/leads/training': typeof AppLeadsTrainingRoute
  '/leads/wizard': typeof AppLeadsWizardRoute
  '/price-books/new': typeof AppPriceBooksNewRoute
  '/team/invites': typeof AppTeamInvitesRoute
  '/team/requests': typeof AppTeamRequestsRoute
  '/admin/assemblies/import': typeof AdminAssembliesImportRoute
  '/admin/companies/$id': typeof AdminCompaniesIdRoute
  '/admin/price-books/new': typeof AdminPriceBooksNewRoute
  '/api/public/sign': typeof ApiPublicSignRoute
  '/invoices/': typeof AppInvoicesIndexRoute
  '/jobs/': typeof AppJobsIndexRoute
  '/leads/': typeof AppLeadsIndexRoute
  '/team/': typeof AppTeamIndexRoute
  '/jobs/$id/contract': typeof AppJobsIdContractRoute
  '/jobs/$id/documents': typeof AppJobsIdDocumentsRoute
  '/jobs/$id/estimate': typeof AppJobsIdEstimateRoute
  '/jobs/$id/invoices': typeof AppJobsIdInvoicesRoute
  '/jobs/$id/measure': typeof AppJobsIdMeasureRoute
  '/jobs/$id/order-form': typeof AppJobsIdOrderFormRoute
  '/jobs/$id/photos': typeof AppJobsIdPhotosRoute
  '/jobs/$id/report': typeof AppJobsIdReportRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/jobs/$id/': typeof AppJobsIdIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/card': typeof AppCardRoute
  '/clients': typeof AppClientsRouteWithChildren
  '/price-books': typeof AppPriceBooksRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/companies': typeof AdminCompaniesRouteWithChildren
  '/admin/content': typeof AdminContentRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/macros': typeof AdminMacrosRoute
  '/admin/measurement-reviews': typeof AdminMeasurementReviewsRoute
  '/admin/memberships': typeof AdminMembershipsRoute
  '/admin/price-books': typeof AdminPriceBooksRouteWithChildren
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/training': typeof AdminTrainingRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/analyze-job-photos': typeof ApiAnalyzeJobPhotosRoute
  '/api/analyze-property': typeof ApiAnalyzePropertyRoute
  '/api/analyze-roof-condition': typeof ApiAnalyzeRoofConditionRoute
  '/api/apply-assembly-import': typeof ApiApplyAssemblyImportRoute
  '/api/auto-add-photo-suggestions': typeof ApiAutoAddPhotoSuggestionsRoute
  '/api/build-roof-estimate': typeof ApiBuildRoofEstimateRoute
  '/api/calibrate-solar': typeof ApiCalibrateSolarRoute
  '/api/import-assembly-pdf': typeof ApiImportAssemblyPdfRoute
  '/api/mapbox-token': typeof ApiMapboxTokenRoute
  '/api/parse-xactimate-pdf': typeof ApiParseXactimatePdfRoute
  '/api/solar-roof-extract': typeof ApiSolarRoofExtractRoute
  '/api/train-from-pdf': typeof ApiTrainFromPdfRoute
  '/c/$slug': typeof CSlugRoute
  '/pay/$token': typeof PayTokenRoute
  '/': typeof AppIndexRoute
  '/admin': typeof AdminIndexRoute
  '/clients/$id': typeof AppClientsIdRoute
  '/invoices/$id': typeof AppInvoicesIdRoute
  '/invoices/new': typeof AppInvoicesNewRoute
  '/jobs/new': typeof AppJobsNewRoute
  '/leads/followup': typeof AppLeadsFollowupRoute
  '/leads/import': typeof AppLeadsImportRoute
  '/leads/list': typeof AppLeadsListRoute
  '/leads/map': typeof AppLeadsMapRoute
  '/leads/pipeline': typeof AppLeadsPipelineRoute
  '/leads/savings': typeof AppLeadsSavingsRoute
  '/leads/training': typeof AppLeadsTrainingRoute
  '/leads/wizard': typeof AppLeadsWizardRoute
  '/price-books/new': typeof AppPriceBooksNewRoute
  '/team/invites': typeof AppTeamInvitesRoute
  '/team/requests': typeof AppTeamRequestsRoute
  '/admin/assemblies/import': typeof AdminAssembliesImportRoute
  '/admin/companies/$id': typeof AdminCompaniesIdRoute
  '/admin/price-books/new': typeof AdminPriceBooksNewRoute
  '/api/public/sign': typeof ApiPublicSignRoute
  '/invoices': typeof AppInvoicesIndexRoute
  '/jobs': typeof AppJobsIndexRoute
  '/leads': typeof AppLeadsIndexRoute
  '/team': typeof AppTeamIndexRoute
  '/jobs/$id/contract': typeof AppJobsIdContractRoute
  '/jobs/$id/documents': typeof AppJobsIdDocumentsRoute
  '/jobs/$id/estimate': typeof AppJobsIdEstimateRoute
  '/jobs/$id/invoices': typeof AppJobsIdInvoicesRoute
  '/jobs/$id/measure': typeof AppJobsIdMeasureRoute
  '/jobs/$id/order-form': typeof AppJobsIdOrderFormRoute
  '/jobs/$id/photos': typeof AppJobsIdPhotosRoute
  '/jobs/$id/report': typeof AppJobsIdReportRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/jobs/$id': typeof AppJobsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_app/card': typeof AppCardRoute
  '/_app/clients': typeof AppClientsRouteWithChildren
  '/_app/leads': typeof AppLeadsRouteWithChildren
  '/_app/price-books': typeof AppPriceBooksRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/team': typeof AppTeamRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/companies': typeof AdminCompaniesRouteWithChildren
  '/admin/content': typeof AdminContentRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/macros': typeof AdminMacrosRoute
  '/admin/measurement-reviews': typeof AdminMeasurementReviewsRoute
  '/admin/memberships': typeof AdminMembershipsRoute
  '/admin/price-books': typeof AdminPriceBooksRouteWithChildren
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/training': typeof AdminTrainingRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/analyze-job-photos': typeof ApiAnalyzeJobPhotosRoute
  '/api/analyze-property': typeof ApiAnalyzePropertyRoute
  '/api/analyze-roof-condition': typeof ApiAnalyzeRoofConditionRoute
  '/api/apply-assembly-import': typeof ApiApplyAssemblyImportRoute
  '/api/auto-add-photo-suggestions': typeof ApiAutoAddPhotoSuggestionsRoute
  '/api/build-roof-estimate': typeof ApiBuildRoofEstimateRoute
  '/api/calibrate-solar': typeof ApiCalibrateSolarRoute
  '/api/import-assembly-pdf': typeof ApiImportAssemblyPdfRoute
  '/api/mapbox-token': typeof ApiMapboxTokenRoute
  '/api/parse-xactimate-pdf': typeof ApiParseXactimatePdfRoute
  '/api/solar-roof-extract': typeof ApiSolarRoofExtractRoute
  '/api/train-from-pdf': typeof ApiTrainFromPdfRoute
  '/c/$slug': typeof CSlugRoute
  '/pay/$token': typeof PayTokenRoute
  '/_app/': typeof AppIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/clients/$id': typeof AppClientsIdRoute
  '/_app/invoices/$id': typeof AppInvoicesIdRoute
  '/_app/invoices/new': typeof AppInvoicesNewRoute
  '/_app/jobs/$id': typeof AppJobsIdRouteWithChildren
  '/_app/jobs/new': typeof AppJobsNewRoute
  '/_app/leads/followup': typeof AppLeadsFollowupRoute
  '/_app/leads/import': typeof AppLeadsImportRoute
  '/_app/leads/list': typeof AppLeadsListRoute
  '/_app/leads/map': typeof AppLeadsMapRoute
  '/_app/leads/pipeline': typeof AppLeadsPipelineRoute
  '/_app/leads/savings': typeof AppLeadsSavingsRoute
  '/_app/leads/training': typeof AppLeadsTrainingRoute
  '/_app/leads/wizard': typeof AppLeadsWizardRoute
  '/_app/price-books/new': typeof AppPriceBooksNewRoute
  '/_app/team/invites': typeof AppTeamInvitesRoute
  '/_app/team/requests': typeof AppTeamRequestsRoute
  '/admin/assemblies/import': typeof AdminAssembliesImportRoute
  '/admin/companies/$id': typeof AdminCompaniesIdRoute
  '/admin/price-books/new': typeof AdminPriceBooksNewRoute
  '/api/public/sign': typeof ApiPublicSignRoute
  '/_app/invoices/': typeof AppInvoicesIndexRoute
  '/_app/jobs/': typeof AppJobsIndexRoute
  '/_app/leads/': typeof AppLeadsIndexRoute
  '/_app/team/': typeof AppTeamIndexRoute
  '/_app/jobs/$id/contract': typeof AppJobsIdContractRoute
  '/_app/jobs/$id/documents': typeof AppJobsIdDocumentsRoute
  '/_app/jobs/$id/estimate': typeof AppJobsIdEstimateRoute
  '/_app/jobs/$id/invoices': typeof AppJobsIdInvoicesRoute
  '/_app/jobs/$id/measure': typeof AppJobsIdMeasureRoute
  '/_app/jobs/$id/order-form': typeof AppJobsIdOrderFormRoute
  '/_app/jobs/$id/photos': typeof AppJobsIdPhotosRoute
  '/_app/jobs/$id/report': typeof AppJobsIdReportRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/_app/jobs/$id/': typeof AppJobsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/profile-setup'
    | '/reset-password'
    | '/signup'
    | '/card'
    | '/clients'
    | '/leads'
    | '/price-books'
    | '/settings'
    | '/team'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/audit'
    | '/admin/companies'
    | '/admin/content'
    | '/admin/emails'
    | '/admin/features'
    | '/admin/macros'
    | '/admin/measurement-reviews'
    | '/admin/memberships'
    | '/admin/price-books'
    | '/admin/reviews'
    | '/admin/support'
    | '/admin/tenants'
    | '/admin/training'
    | '/admin/users'
    | '/api/analyze-job-photos'
    | '/api/analyze-property'
    | '/api/analyze-roof-condition'
    | '/api/apply-assembly-import'
    | '/api/auto-add-photo-suggestions'
    | '/api/build-roof-estimate'
    | '/api/calibrate-solar'
    | '/api/import-assembly-pdf'
    | '/api/mapbox-token'
    | '/api/parse-xactimate-pdf'
    | '/api/solar-roof-extract'
    | '/api/train-from-pdf'
    | '/c/$slug'
    | '/pay/$token'
    | '/admin/'
    | '/clients/$id'
    | '/invoices/$id'
    | '/invoices/new'
    | '/jobs/$id'
    | '/jobs/new'
    | '/leads/followup'
    | '/leads/import'
    | '/leads/list'
    | '/leads/map'
    | '/leads/pipeline'
    | '/leads/savings'
    | '/leads/training'
    | '/leads/wizard'
    | '/price-books/new'
    | '/team/invites'
    | '/team/requests'
    | '/admin/assemblies/import'
    | '/admin/companies/$id'
    | '/admin/price-books/new'
    | '/api/public/sign'
    | '/invoices/'
    | '/jobs/'
    | '/leads/'
    | '/team/'
    | '/jobs/$id/contract'
    | '/jobs/$id/documents'
    | '/jobs/$id/estimate'
    | '/jobs/$id/invoices'
    | '/jobs/$id/measure'
    | '/jobs/$id/order-form'
    | '/jobs/$id/photos'
    | '/jobs/$id/report'
    | '/api/public/payments/webhook'
    | '/jobs/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/profile-setup'
    | '/reset-password'
    | '/signup'
    | '/card'
    | '/clients'
    | '/price-books'
    | '/settings'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/audit'
    | '/admin/companies'
    | '/admin/content'
    | '/admin/emails'
    | '/admin/features'
    | '/admin/macros'
    | '/admin/measurement-reviews'
    | '/admin/memberships'
    | '/admin/price-books'
    | '/admin/reviews'
    | '/admin/support'
    | '/admin/tenants'
    | '/admin/training'
    | '/admin/users'
    | '/api/analyze-job-photos'
    | '/api/analyze-property'
    | '/api/analyze-roof-condition'
    | '/api/apply-assembly-import'
    | '/api/auto-add-photo-suggestions'
    | '/api/build-roof-estimate'
    | '/api/calibrate-solar'
    | '/api/import-assembly-pdf'
    | '/api/mapbox-token'
    | '/api/parse-xactimate-pdf'
    | '/api/solar-roof-extract'
    | '/api/train-from-pdf'
    | '/c/$slug'
    | '/pay/$token'
    | '/'
    | '/admin'
    | '/clients/$id'
    | '/invoices/$id'
    | '/invoices/new'
    | '/jobs/new'
    | '/leads/followup'
    | '/leads/import'
    | '/leads/list'
    | '/leads/map'
    | '/leads/pipeline'
    | '/leads/savings'
    | '/leads/training'
    | '/leads/wizard'
    | '/price-books/new'
    | '/team/invites'
    | '/team/requests'
    | '/admin/assemblies/import'
    | '/admin/companies/$id'
    | '/admin/price-books/new'
    | '/api/public/sign'
    | '/invoices'
    | '/jobs'
    | '/leads'
    | '/team'
    | '/jobs/$id/contract'
    | '/jobs/$id/documents'
    | '/jobs/$id/estimate'
    | '/jobs/$id/invoices'
    | '/jobs/$id/measure'
    | '/jobs/$id/order-form'
    | '/jobs/$id/photos'
    | '/jobs/$id/report'
    | '/api/public/payments/webhook'
    | '/jobs/$id'
  id:
    | '__root__'
    | '/_app'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/profile-setup'
    | '/reset-password'
    | '/signup'
    | '/_app/card'
    | '/_app/clients'
    | '/_app/leads'
    | '/_app/price-books'
    | '/_app/settings'
    | '/_app/team'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/audit'
    | '/admin/companies'
    | '/admin/content'
    | '/admin/emails'
    | '/admin/features'
    | '/admin/macros'
    | '/admin/measurement-reviews'
    | '/admin/memberships'
    | '/admin/price-books'
    | '/admin/reviews'
    | '/admin/support'
    | '/admin/tenants'
    | '/admin/training'
    | '/admin/users'
    | '/api/analyze-job-photos'
    | '/api/analyze-property'
    | '/api/analyze-roof-condition'
    | '/api/apply-assembly-import'
    | '/api/auto-add-photo-suggestions'
    | '/api/build-roof-estimate'
    | '/api/calibrate-solar'
    | '/api/import-assembly-pdf'
    | '/api/mapbox-token'
    | '/api/parse-xactimate-pdf'
    | '/api/solar-roof-extract'
    | '/api/train-from-pdf'
    | '/c/$slug'
    | '/pay/$token'
    | '/_app/'
    | '/admin/'
    | '/_app/clients/$id'
    | '/_app/invoices/$id'
    | '/_app/invoices/new'
    | '/_app/jobs/$id'
    | '/_app/jobs/new'
    | '/_app/leads/followup'
    | '/_app/leads/import'
    | '/_app/leads/list'
    | '/_app/leads/map'
    | '/_app/leads/pipeline'
    | '/_app/leads/savings'
    | '/_app/leads/training'
    | '/_app/leads/wizard'
    | '/_app/price-books/new'
    | '/_app/team/invites'
    | '/_app/team/requests'
    | '/admin/assemblies/import'
    | '/admin/companies/$id'
    | '/admin/price-books/new'
    | '/api/public/sign'
    | '/_app/invoices/'
    | '/_app/jobs/'
    | '/_app/leads/'
    | '/_app/team/'
    | '/_app/jobs/$id/contract'
    | '/_app/jobs/$id/documents'
    | '/_app/jobs/$id/estimate'
    | '/_app/jobs/$id/invoices'
    | '/_app/jobs/$id/measure'
    | '/_app/jobs/$id/order-form'
    | '/_app/jobs/$id/photos'
    | '/_app/jobs/$id/report'
    | '/api/public/payments/webhook'
    | '/_app/jobs/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileSetupRoute: typeof ProfileSetupRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiAnalyzeJobPhotosRoute: typeof ApiAnalyzeJobPhotosRoute
  ApiAnalyzePropertyRoute: typeof ApiAnalyzePropertyRoute
  ApiAnalyzeRoofConditionRoute: typeof ApiAnalyzeRoofConditionRoute
  ApiApplyAssemblyImportRoute: typeof ApiApplyAssemblyImportRoute
  ApiAutoAddPhotoSuggestionsRoute: typeof ApiAutoAddPhotoSuggestionsRoute
  ApiBuildRoofEstimateRoute: typeof ApiBuildRoofEstimateRoute
  ApiCalibrateSolarRoute: typeof ApiCalibrateSolarRoute
  ApiImportAssemblyPdfRoute: typeof ApiImportAssemblyPdfRoute
  ApiMapboxTokenRoute: typeof ApiMapboxTokenRoute
  ApiParseXactimatePdfRoute: typeof ApiParseXactimatePdfRoute
  ApiSolarRoofExtractRoute: typeof ApiSolarRoofExtractRoute
  ApiTrainFromPdfRoute: typeof ApiTrainFromPdfRoute
  CSlugRoute: typeof CSlugRoute
  PayTokenRoute: typeof PayTokenRoute
  ApiPublicSignRoute: typeof ApiPublicSignRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-setup': {
      id: '/profile-setup'
      path: '/profile-setup'
      fullPath: '/profile-setup'
      preLoaderRoute: typeof ProfileSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/pay/$token': {
      id: '/pay/$token'
      path: '/pay/$token'
      fullPath: '/pay/$token'
      preLoaderRoute: typeof PayTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/train-from-pdf': {
      id: '/api/train-from-pdf'
      path: '/api/train-from-pdf'
      fullPath: '/api/train-from-pdf'
      preLoaderRoute: typeof ApiTrainFromPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/solar-roof-extract': {
      id: '/api/solar-roof-extract'
      path: '/api/solar-roof-extract'
      fullPath: '/api/solar-roof-extract'
      preLoaderRoute: typeof ApiSolarRoofExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/parse-xactimate-pdf': {
      id: '/api/parse-xactimate-pdf'
      path: '/api/parse-xactimate-pdf'
      fullPath: '/api/parse-xactimate-pdf'
      preLoaderRoute: typeof ApiParseXactimatePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mapbox-token': {
      id: '/api/mapbox-token'
      path: '/api/mapbox-token'
      fullPath: '/api/mapbox-token'
      preLoaderRoute: typeof ApiMapboxTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import-assembly-pdf': {
      id: '/api/import-assembly-pdf'
      path: '/api/import-assembly-pdf'
      fullPath: '/api/import-assembly-pdf'
      preLoaderRoute: typeof ApiImportAssemblyPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calibrate-solar': {
      id: '/api/calibrate-solar'
      path: '/api/calibrate-solar'
      fullPath: '/api/calibrate-solar'
      preLoaderRoute: typeof ApiCalibrateSolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/build-roof-estimate': {
      id: '/api/build-roof-estimate'
      path: '/api/build-roof-estimate'
      fullPath: '/api/build-roof-estimate'
      preLoaderRoute: typeof ApiBuildRoofEstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auto-add-photo-suggestions': {
      id: '/api/auto-add-photo-suggestions'
      path: '/api/auto-add-photo-suggestions'
      fullPath: '/api/auto-add-photo-suggestions'
      preLoaderRoute: typeof ApiAutoAddPhotoSuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/apply-assembly-import': {
      id: '/api/apply-assembly-import'
      path: '/api/apply-assembly-import'
      fullPath: '/api/apply-assembly-import'
      preLoaderRoute: typeof ApiApplyAssemblyImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze-roof-condition': {
      id: '/api/analyze-roof-condition'
      path: '/api/analyze-roof-condition'
      fullPath: '/api/analyze-roof-condition'
      preLoaderRoute: typeof ApiAnalyzeRoofConditionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze-property': {
      id: '/api/analyze-property'
      path: '/api/analyze-property'
      fullPath: '/api/analyze-property'
      preLoaderRoute: typeof ApiAnalyzePropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze-job-photos': {
      id: '/api/analyze-job-photos'
      path: '/api/analyze-job-photos'
      fullPath: '/api/analyze-job-photos'
      preLoaderRoute: typeof ApiAnalyzeJobPhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/training': {
      id: '/admin/training'
      path: '/training'
      fullPath: '/admin/training'
      preLoaderRoute: typeof AdminTrainingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tenants': {
      id: '/admin/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/price-books': {
      id: '/admin/price-books'
      path: '/price-books'
      fullPath: '/admin/price-books'
      preLoaderRoute: typeof AdminPriceBooksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/memberships': {
      id: '/admin/memberships'
      path: '/memberships'
      fullPath: '/admin/memberships'
      preLoaderRoute: typeof AdminMembershipsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/measurement-reviews': {
      id: '/admin/measurement-reviews'
      path: '/measurement-reviews'
      fullPath: '/admin/measurement-reviews'
      preLoaderRoute: typeof AdminMeasurementReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/macros': {
      id: '/admin/macros'
      path: '/macros'
      fullPath: '/admin/macros'
      preLoaderRoute: typeof AdminMacrosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/features': {
      id: '/admin/features'
      path: '/features'
      fullPath: '/admin/features'
      preLoaderRoute: typeof AdminFeaturesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/emails': {
      id: '/admin/emails'
      path: '/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AdminEmailsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/companies': {
      id: '/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AdminCompaniesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/price-books': {
      id: '/_app/price-books'
      path: '/price-books'
      fullPath: '/price-books'
      preLoaderRoute: typeof AppPriceBooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients': {
      id: '/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/card': {
      id: '/_app/card'
      path: '/card'
      fullPath: '/card'
      preLoaderRoute: typeof AppCardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team/': {
      id: '/_app/team/'
      path: '/'
      fullPath: '/team/'
      preLoaderRoute: typeof AppTeamIndexRouteImport
      parentRoute: typeof AppTeamRoute
    }
    '/_app/leads/': {
      id: '/_app/leads/'
      path: '/'
      fullPath: '/leads/'
      preLoaderRoute: typeof AppLeadsIndexRouteImport
      parentRoute: typeof AppLeadsRoute
    }
    '/_app/jobs/': {
      id: '/_app/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AppJobsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/': {
      id: '/_app/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/sign': {
      id: '/api/public/sign'
      path: '/api/public/sign'
      fullPath: '/api/public/sign'
      preLoaderRoute: typeof ApiPublicSignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/price-books/new': {
      id: '/admin/price-books/new'
      path: '/new'
      fullPath: '/admin/price-books/new'
      preLoaderRoute: typeof AdminPriceBooksNewRouteImport
      parentRoute: typeof AdminPriceBooksRoute
    }
    '/admin/companies/$id': {
      id: '/admin/companies/$id'
      path: '/$id'
      fullPath: '/admin/companies/$id'
      preLoaderRoute: typeof AdminCompaniesIdRouteImport
      parentRoute: typeof AdminCompaniesRoute
    }
    '/admin/assemblies/import': {
      id: '/admin/assemblies/import'
      path: '/assemblies/import'
      fullPath: '/admin/assemblies/import'
      preLoaderRoute: typeof AdminAssembliesImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/team/requests': {
      id: '/_app/team/requests'
      path: '/requests'
      fullPath: '/team/requests'
      preLoaderRoute: typeof AppTeamRequestsRouteImport
      parentRoute: typeof AppTeamRoute
    }
    '/_app/team/invites': {
      id: '/_app/team/invites'
      path: '/invites'
      fullPath: '/team/invites'
      preLoaderRoute: typeof AppTeamInvitesRouteImport
      parentRoute: typeof AppTeamRoute
    }
    '/_app/price-books/new': {
      id: '/_app/price-books/new'
      path: '/new'
      fullPath: '/price-books/new'
      preLoaderRoute: typeof AppPriceBooksNewRouteImport
      parentRoute: typeof AppPriceBooksRoute
    }
    '/_app/leads/wizard': {
      id: '/_app/leads/wizard'
      path: '/wizard'
      fullPath: '/leads/wizard'
      preLoaderRoute: typeof AppLeadsWizardRouteImport
      parentRoute: typeof AppLeadsRoute
    }
    '/_app/leads/training': {
      id: '/_app/leads/training'
      path: '/training'
      fullPath: '/leads/training'
      preLoaderRoute: typeof AppLeadsTrainingRouteImport
      parentRoute: typeof AppLeadsRoute
    }
    '/_app/leads/savings': {
      id: '/_app/leads/savings'
      path: '/savings'
      fullPath: '/leads/savings'
      preLoaderRoute: typeof AppLeadsSavingsRouteImport
      parentRoute: typeof AppLeadsRoute
    }
    '/_app/leads/pipeline': {
      id: '/_app/leads/pipeline'
      path: '/pipeline'
      fullPath: '/leads/pipeline'
      preLoaderRoute: typeof AppLeadsPipelineRouteImport
      parentRoute: typeof AppLeadsRoute
    }
    '/_app/leads/map': {
      id: '/_app/leads/map'
      path: '/map'
      fullPath: '/leads/map'
      preLoaderRoute: typeof AppLeadsMapRouteImport
      parentRoute: typeof AppLeadsRoute
    }
    '/_app/leads/list': {
      id: '/_app/leads/list'
      path: '/list'
      fullPath: '/leads/list'
      preLoaderRoute: typeof AppLeadsListRouteImport
      parentRoute: typeof AppLeadsRoute
    }
    '/_app/leads/import': {
      id: '/_app/leads/import'
      path: '/import'
      fullPath: '/leads/import'
      preLoaderRoute: typeof AppLeadsImportRouteImport
      parentRoute: typeof AppLeadsRoute
    }
    '/_app/leads/followup': {
      id: '/_app/leads/followup'
      path: '/followup'
      fullPath: '/leads/followup'
      preLoaderRoute: typeof AppLeadsFollowupRouteImport
      parentRoute: typeof AppLeadsRoute
    }
    '/_app/jobs/new': {
      id: '/_app/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof AppJobsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/$id': {
      id: '/_app/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof AppJobsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/new': {
      id: '/_app/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AppInvoicesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/$id': {
      id: '/_app/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof AppInvoicesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/$id': {
      id: '/_app/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AppClientsIdRouteImport
      parentRoute: typeof AppClientsRoute
    }
    '/_app/jobs/$id/': {
      id: '/_app/jobs/$id/'
      path: '/'
      fullPath: '/jobs/$id/'
      preLoaderRoute: typeof AppJobsIdIndexRouteImport
      parentRoute: typeof AppJobsIdRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/jobs/$id/report': {
      id: '/_app/jobs/$id/report'
      path: '/report'
      fullPath: '/jobs/$id/report'
      preLoaderRoute: typeof AppJobsIdReportRouteImport
      parentRoute: typeof AppJobsIdRoute
    }
    '/_app/jobs/$id/photos': {
      id: '/_app/jobs/$id/photos'
      path: '/photos'
      fullPath: '/jobs/$id/photos'
      preLoaderRoute: typeof AppJobsIdPhotosRouteImport
      parentRoute: typeof AppJobsIdRoute
    }
    '/_app/jobs/$id/order-form': {
      id: '/_app/jobs/$id/order-form'
      path: '/order-form'
      fullPath: '/jobs/$id/order-form'
      preLoaderRoute: typeof AppJobsIdOrderFormRouteImport
      parentRoute: typeof AppJobsIdRoute
    }
    '/_app/jobs/$id/measure': {
      id: '/_app/jobs/$id/measure'
      path: '/measure'
      fullPath: '/jobs/$id/measure'
      preLoaderRoute: typeof AppJobsIdMeasureRouteImport
      parentRoute: typeof AppJobsIdRoute
    }
    '/_app/jobs/$id/invoices': {
      id: '/_app/jobs/$id/invoices'
      path: '/invoices'
      fullPath: '/jobs/$id/invoices'
      preLoaderRoute: typeof AppJobsIdInvoicesRouteImport
      parentRoute: typeof AppJobsIdRoute
    }
    '/_app/jobs/$id/estimate': {
      id: '/_app/jobs/$id/estimate'
      path: '/estimate'
      fullPath: '/jobs/$id/estimate'
      preLoaderRoute: typeof AppJobsIdEstimateRouteImport
      parentRoute: typeof AppJobsIdRoute
    }
    '/_app/jobs/$id/documents': {
      id: '/_app/jobs/$id/documents'
      path: '/documents'
      fullPath: '/jobs/$id/documents'
      preLoaderRoute: typeof AppJobsIdDocumentsRouteImport
      parentRoute: typeof AppJobsIdRoute
    }
    '/_app/jobs/$id/contract': {
      id: '/_app/jobs/$id/contract'
      path: '/contract'
      fullPath: '/jobs/$id/contract'
      preLoaderRoute: typeof AppJobsIdContractRouteImport
      parentRoute: typeof AppJobsIdRoute
    }
  }
}

interface AppClientsRouteChildren {
  AppClientsIdRoute: typeof AppClientsIdRoute
}

const AppClientsRouteChildren: AppClientsRouteChildren = {
  AppClientsIdRoute: AppClientsIdRoute,
}

const AppClientsRouteWithChildren = AppClientsRoute._addFileChildren(
  AppClientsRouteChildren,
)

interface AppLeadsRouteChildren {
  AppLeadsFollowupRoute: typeof AppLeadsFollowupRoute
  AppLeadsImportRoute: typeof AppLeadsImportRoute
  AppLeadsListRoute: typeof AppLeadsListRoute
  AppLeadsMapRoute: typeof AppLeadsMapRoute
  AppLeadsPipelineRoute: typeof AppLeadsPipelineRoute
  AppLeadsSavingsRoute: typeof AppLeadsSavingsRoute
  AppLeadsTrainingRoute: typeof AppLeadsTrainingRoute
  AppLeadsWizardRoute: typeof AppLeadsWizardRoute
  AppLeadsIndexRoute: typeof AppLeadsIndexRoute
}

const AppLeadsRouteChildren: AppLeadsRouteChildren = {
  AppLeadsFollowupRoute: AppLeadsFollowupRoute,
  AppLeadsImportRoute: AppLeadsImportRoute,
  AppLeadsListRoute: AppLeadsListRoute,
  AppLeadsMapRoute: AppLeadsMapRoute,
  AppLeadsPipelineRoute: AppLeadsPipelineRoute,
  AppLeadsSavingsRoute: AppLeadsSavingsRoute,
  AppLeadsTrainingRoute: AppLeadsTrainingRoute,
  AppLeadsWizardRoute: AppLeadsWizardRoute,
  AppLeadsIndexRoute: AppLeadsIndexRoute,
}

const AppLeadsRouteWithChildren = AppLeadsRoute._addFileChildren(
  AppLeadsRouteChildren,
)

interface AppPriceBooksRouteChildren {
  AppPriceBooksNewRoute: typeof AppPriceBooksNewRoute
}

const AppPriceBooksRouteChildren: AppPriceBooksRouteChildren = {
  AppPriceBooksNewRoute: AppPriceBooksNewRoute,
}

const AppPriceBooksRouteWithChildren = AppPriceBooksRoute._addFileChildren(
  AppPriceBooksRouteChildren,
)

interface AppTeamRouteChildren {
  AppTeamInvitesRoute: typeof AppTeamInvitesRoute
  AppTeamRequestsRoute: typeof AppTeamRequestsRoute
  AppTeamIndexRoute: typeof AppTeamIndexRoute
}

const AppTeamRouteChildren: AppTeamRouteChildren = {
  AppTeamInvitesRoute: AppTeamInvitesRoute,
  AppTeamRequestsRoute: AppTeamRequestsRoute,
  AppTeamIndexRoute: AppTeamIndexRoute,
}

const AppTeamRouteWithChildren =
  AppTeamRoute._addFileChildren(AppTeamRouteChildren)

interface AppJobsIdRouteChildren {
  AppJobsIdContractRoute: typeof AppJobsIdContractRoute
  AppJobsIdDocumentsRoute: typeof AppJobsIdDocumentsRoute
  AppJobsIdEstimateRoute: typeof AppJobsIdEstimateRoute
  AppJobsIdInvoicesRoute: typeof AppJobsIdInvoicesRoute
  AppJobsIdMeasureRoute: typeof AppJobsIdMeasureRoute
  AppJobsIdOrderFormRoute: typeof AppJobsIdOrderFormRoute
  AppJobsIdPhotosRoute: typeof AppJobsIdPhotosRoute
  AppJobsIdReportRoute: typeof AppJobsIdReportRoute
  AppJobsIdIndexRoute: typeof AppJobsIdIndexRoute
}

const AppJobsIdRouteChildren: AppJobsIdRouteChildren = {
  AppJobsIdContractRoute: AppJobsIdContractRoute,
  AppJobsIdDocumentsRoute: AppJobsIdDocumentsRoute,
  AppJobsIdEstimateRoute: AppJobsIdEstimateRoute,
  AppJobsIdInvoicesRoute: AppJobsIdInvoicesRoute,
  AppJobsIdMeasureRoute: AppJobsIdMeasureRoute,
  AppJobsIdOrderFormRoute: AppJobsIdOrderFormRoute,
  AppJobsIdPhotosRoute: AppJobsIdPhotosRoute,
  AppJobsIdReportRoute: AppJobsIdReportRoute,
  AppJobsIdIndexRoute: AppJobsIdIndexRoute,
}

const AppJobsIdRouteWithChildren = AppJobsIdRoute._addFileChildren(
  AppJobsIdRouteChildren,
)

interface AppRouteChildren {
  AppCardRoute: typeof AppCardRoute
  AppClientsRoute: typeof AppClientsRouteWithChildren
  AppLeadsRoute: typeof AppLeadsRouteWithChildren
  AppPriceBooksRoute: typeof AppPriceBooksRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamRoute: typeof AppTeamRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppInvoicesIdRoute: typeof AppInvoicesIdRoute
  AppInvoicesNewRoute: typeof AppInvoicesNewRoute
  AppJobsIdRoute: typeof AppJobsIdRouteWithChildren
  AppJobsNewRoute: typeof AppJobsNewRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
  AppJobsIndexRoute: typeof AppJobsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCardRoute: AppCardRoute,
  AppClientsRoute: AppClientsRouteWithChildren,
  AppLeadsRoute: AppLeadsRouteWithChildren,
  AppPriceBooksRoute: AppPriceBooksRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamRoute: AppTeamRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppInvoicesIdRoute: AppInvoicesIdRoute,
  AppInvoicesNewRoute: AppInvoicesNewRoute,
  AppJobsIdRoute: AppJobsIdRouteWithChildren,
  AppJobsNewRoute: AppJobsNewRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
  AppJobsIndexRoute: AppJobsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminCompaniesRouteChildren {
  AdminCompaniesIdRoute: typeof AdminCompaniesIdRoute
}

const AdminCompaniesRouteChildren: AdminCompaniesRouteChildren = {
  AdminCompaniesIdRoute: AdminCompaniesIdRoute,
}

const AdminCompaniesRouteWithChildren = AdminCompaniesRoute._addFileChildren(
  AdminCompaniesRouteChildren,
)

interface AdminPriceBooksRouteChildren {
  AdminPriceBooksNewRoute: typeof AdminPriceBooksNewRoute
}

const AdminPriceBooksRouteChildren: AdminPriceBooksRouteChildren = {
  AdminPriceBooksNewRoute: AdminPriceBooksNewRoute,
}

const AdminPriceBooksRouteWithChildren = AdminPriceBooksRoute._addFileChildren(
  AdminPriceBooksRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCompaniesRoute: typeof AdminCompaniesRouteWithChildren
  AdminContentRoute: typeof AdminContentRoute
  AdminEmailsRoute: typeof AdminEmailsRoute
  AdminFeaturesRoute: typeof AdminFeaturesRoute
  AdminMacrosRoute: typeof AdminMacrosRoute
  AdminMeasurementReviewsRoute: typeof AdminMeasurementReviewsRoute
  AdminMembershipsRoute: typeof AdminMembershipsRoute
  AdminPriceBooksRoute: typeof AdminPriceBooksRouteWithChildren
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminTenantsRoute: typeof AdminTenantsRoute
  AdminTrainingRoute: typeof AdminTrainingRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAssembliesImportRoute: typeof AdminAssembliesImportRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCompaniesRoute: AdminCompaniesRouteWithChildren,
  AdminContentRoute: AdminContentRoute,
  AdminEmailsRoute: AdminEmailsRoute,
  AdminFeaturesRoute: AdminFeaturesRoute,
  AdminMacrosRoute: AdminMacrosRoute,
  AdminMeasurementReviewsRoute: AdminMeasurementReviewsRoute,
  AdminMembershipsRoute: AdminMembershipsRoute,
  AdminPriceBooksRoute: AdminPriceBooksRouteWithChildren,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminTenantsRoute: AdminTenantsRoute,
  AdminTrainingRoute: AdminTrainingRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAssembliesImportRoute: AdminAssembliesImportRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileSetupRoute: ProfileSetupRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiAnalyzeJobPhotosRoute: ApiAnalyzeJobPhotosRoute,
  ApiAnalyzePropertyRoute: ApiAnalyzePropertyRoute,
  ApiAnalyzeRoofConditionRoute: ApiAnalyzeRoofConditionRoute,
  ApiApplyAssemblyImportRoute: ApiApplyAssemblyImportRoute,
  ApiAutoAddPhotoSuggestionsRoute: ApiAutoAddPhotoSuggestionsRoute,
  ApiBuildRoofEstimateRoute: ApiBuildRoofEstimateRoute,
  ApiCalibrateSolarRoute: ApiCalibrateSolarRoute,
  ApiImportAssemblyPdfRoute: ApiImportAssemblyPdfRoute,
  ApiMapboxTokenRoute: ApiMapboxTokenRoute,
  ApiParseXactimatePdfRoute: ApiParseXactimatePdfRoute,
  ApiSolarRoofExtractRoute: ApiSolarRoofExtractRoute,
  ApiTrainFromPdfRoute: ApiTrainFromPdfRoute,
  CSlugRoute: CSlugRoute,
  PayTokenRoute: PayTokenRoute,
  ApiPublicSignRoute: ApiPublicSignRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
